name: timeassistapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-232.0.dev <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_pickers: ^2.1.9
  http: ^0.13.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
